spring.application.name=enceladus

spring.dataSource.url=jdbc:mysql://127.0.0.1:3306/enceladus
spring.dataSource.driverClassName=com.mysql.cj.jdbc.Driver
spring.dataSource.username=root
spring.dataSource.password=Umesh321
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=True
